name: easy_park
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.17
  google_fonts: ^6.1.0
  http: ^1.3.0
  shared_preferences: ^2.0.15
  email_validator: ^2.1.17
  rename: ^3.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  image_picker: ^1.0.4  
  intl: ^0.19.0
  sqflite: ^2.3.0
  path_provider: ^2.1.2
  flutter_launcher_icons: ^0.13.1
  path: ^1.8.3
  encrypt: ^5.0.3
  flutter_secure_storage: ^9.2.4
  http_parser: ^4.0.2
  flutter_dotenv: ^5.0.2
  mobile_scanner: ^3.2.0
  flutter_localizations:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon.png"
  adaptive_icon_background: "#ffffff"
  min_sdk_android: 21
